### ISSUE TITLE
JSGI compatibility

### ISSUE THREAD

**Issue by tlrobinson** [mjackson/strata#2]
JSGI is a fairly popular Rack/WSGI-like API in JavaScript, including Node: https://github.com/joyent/node/wiki/modules#wiki-middleware-jsgi (as well as Ringo, Akshell, Narwhal, Pintura). You should consider aligning your API with JSGI. Let me know if you need assistance.

**Comment by mjackson** [comment]
JSGI is not able to take advantage of node's ability to serve responses asynchronously because the spec doesn't allow for it. JSGI specifies that the return value of an app must be the [status, headers, body], whereas Strata specifies that the return value of an app is not important and that the app's callback should be used to serve the response instead.

This is an API incompatibility that cannot be ignored. The most developed lib I've seen up to this point to get JSGI working on node (https://github.com/kriszyp/jsgi-node) isn't able to get asynchronous responses working properly. Instead, it just does a `body.forEach` (see https://github.com/kriszyp/jsgi-node/blob/master/lib/jsgi-node.js#L167) to write each piece out to the response synchronously.

**Comment by tlrobinson** [comment]
Kris Zyp's "jsgi-node" absolutely does support streaming. As does Kris Kowal's "q-http" and "jaque" framework.

There have been lots of discussion on asynchronous/streaming in JSGI, but perhaps it hasn't made it's way into the specs you've looked at. Promises are one way, fibers are another.

Foreach-able "streams" w/ promises and Node streams are pretty much equivalent (and yes, JSGI w/ promises can handle back pressure, though I'm not sure if there are any public implementations yet)

**Comment by kriskowal** [comment]
In Jaque and Q-HTTP, you have lots of options for both streaming and delayed response.

For delayed response, you can return a promise for the response.

``` javascript
Server(function (request) {
    return delayed(null, 1000).then(function () {
        return {status, headers, body};
    });
})
```

You can use a forEachable stream, as noted. There are lots of ways to make this pretty using Stream objects.

You can also use Node directly because you get the Node response as a second argument.  This is good since you can use JSGI for routing middleware and then use Node's streaming at your endpoint.  This is relatively new and I might adjust it (since you lose the ability to log time responses, adjust headers, and that kind of thing in middleware if you detach from the stack)

``` javascript
Server(function (request, response) {
    …
});
```

**Comment by tlrobinson** [comment]
Regarding https://github.com/kriszyp/jsgi-node/blob/master/lib/jsgi-node.js#L167 :

In the streaming case the forEach method returns a promise, which indicates the response body has not finished streaming. The callback provided to forEach can then be asynchronously called. Once that promise is resolved the response has finished.

To handle back pressure you'd simply return a promise from the forEach callback that gets resolved when the back pressure is relieved.

**Comment by jmoyers** [comment]
Are promises and fibers the only available abstractions for JSGI with streams -- both suck imo? ReadableStream is great, and I think Node core team will continue to invest in this abstraction. Is there a way to use ReadableStream as the construct of choice and still have an adapter for JSGI?

Not a huge fan of the syntax presented in the reference modules you pointed out:

```
require("jsgi-node").start(
    SomeJSGIMiddleWare(
        OtherJSGIMiddleWare(
            Node(function(request, response){
                // request and response conform to Node's HTTP API
            })
        )
    )
);
```

Less readable than the typical .use syntax from express/strata.

**Comment by tlrobinson** [comment]
Here's a simple adapter to turn readable Node streams into readable "forEach-able" streams:

```
function forEach(callback) {
    this.on("data", function(chunk) {
        var resume = callback(chunk);
        if (resume) {
            this.pause();
            Q.when(resume, this.resume);
        }
    });
    var end = Q.defer();
    this.on("end", end.resolve);
    return end.promise;
}
```

You can either patch Stream (`Stream.prototype.forEach = forEach`) or have a simple conversion function (`function readableToForEachable(readable) { return { forEach : forEach.bind(readable) }; }`)

The following will then work (yes, including streaming and throttling support):

```
function app(request) {
    return {
        status : 200,
        headers : { "Content-Type" : "text/plain" },
        body : fs.createReadStream("test.js")
    };
}
```

Regarding ".use()" syntax, that's pure suger. You can easily build the same on top of JSGI (in fact my initial version had that but I didn't find it necessary so I took it out of the core: https://github.com/tlrobinson/jack/blob/854d4c03e1c0d81a53e79ccbd7a1ca01b4d5694e/lib/jack/builder.js )

**Comment by kriskowal** [comment]
These are Node IO adapters that adapt ReadableStream with forEach and read functions. I will probably augment these with more iterator / lazy-array functions but they haven't failed me yet.  I'll look into using a Pipe so you can write to a readable stream in a handler.

https://github.com/kriskowal/q-io/blob/master/q-io.js

The .use() stuff is great and totally worthwhile at this level of abstraction. It would be good to join forces on the underlying layer so we can share middleware with each other.

**Comment by nrstott** [comment]
Why would you say that jsgi-node does not allow for streaming responses?  It most certainly does.  I've even got an example of that in Bogart which depends on jsgi-node.

**Comment by mjackson** [comment]
@tlrobinson My apologies for stating that JSGI simply doesn't support streaming. You've obviously accounted for it with promises, so I was wrong.

However (and this is where we may have to agree to disagree), promises are simply not an acceptable abstraction to use in a node framework nowadays. They were removed from node core a long time ago in favor of callbacks. That's the API that the vast majority of users are familiar with, and it's the only one that makes sense for a node library intended for use by a large audience.

As far as compatibility with JSGI goes, I'm not interested in making Strata work on any platforms besides node so I don't see much of a point in doing it. If users want to use JSGI on node, they already have that option. The goal of this project is more narrow than that.

I'd really love to join forces as @kriskowal suggests at some layer because I really have a lot of respect for the work that you've done, but our philosophies may differ to the point that it doesn't make sense for us to do so.

**Comment by mjackson** [comment]
Tabling this discussion for now.
