### ISSUE TITLE
Callback signature

### ISSUE THREAD

**Issue by jmoyers** [mjackson/strata#3]
```
   callback(200, {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(content).toString()
    }, content);
```

Would you consider reversing the default signature to (content, [status, [headers]]), where default status = 200, default headers something like:

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 20964
Connection: keep-alive
```

When the response is a known string (buffered). Drop content-length and change to transfer-encoding chunked?

**Comment by mjackson** [comment]
I'm actually very open to this idea. It makes sense to have the most variable arguments come first and assume default values for those that come later. I want to let this idea simmer for a bit though. For one, it would require lots of changes so should probably be reserved for a major release (that breaks backwards compat).

**Comment by ixti** [comment]
I vote for similarity to Rack :))

**Comment by mjackson** [comment]
Yes, I'm leaning that way as well. The main problem is that if some arguments are considered optional then every piece of middleware in the stack needs to handle the defaults in the exact same way. Otherwise, you'll end up with a system that isn't very well defined. What strata really needs is a small Sinatra-like library to sit on top of it that can provide all the syntactic sugar for those who want it.

**Comment by mjackson** [comment]
I've decided to resolve this using `strata.Response` for now. `strata.Response` takes the body, headers, and status arguments in that order, and they're all optional.
