### ISSUE TITLE
Strata Serving Directory

### ISSUE THREAD

**Issue by iammerrick** [mjackson/strata#32]
Was wondering, the default for running `strata`; perhaps making it a little smarter, to where if it can't find app.js to serve the current directory? I am happy to dig in and make a pull request if you are interested?

**Comment by mjackson** [comment]
It would be a simple tweak to bin/strata, but I'm not sure if it would confuse people or not. I personally like software to fail hard and fast when I do something wrong so that I know what I did wrong and how to avoid it in the future. Someone intending to run an app might want to see a "Could not find app.js" error message instead of everything running fine. Thoughts?

**Comment by iammerrick** [comment]
Thats interesting and I can absolutely see your perspective. However I would argue that since node.js it self doesn't infer an entry point and throws you into the REPL, I wouldn't expect strata to infer an entry point. Also, since there is no standardization in the community on app.js (you see server.js all the time :-) I think that is more of  preference thing. I don't mind the -d, was just wondering how open you would be to changing the current functionality.

**Comment by shoxty** [comment]
Defaulting to server the current directory would be pretty hot.

**Comment by mjackson** [comment]
Sorry for letting this one sit for so long! :)
